pipeline {
    agent {
        kubernetes {
            yaml '''
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: maven
                  image: maven:3.9.9-eclipse-temurin-21
                  command:
                  - sleep
                  args:
                  - infinity
                  volumeMounts:
                  - name: maven-cache
                    mountPath: /root/.m2
                volumes:
                - name: maven-cache
                  emptyDir: {}
            '''
        }
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                container('maven') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                container('maven') {
                    sh './jenkins/scripts/deliver.sh' 
                }
            }
        }
    }
}